version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'sentimentAnalysis'
    working_dir: '/root/'
    tty: true
    volumes:
      - ../sentimentAnalysis:/root/sentimentAnalysis
